[platformio]
default_envs = waveshare-esp32s3-touch-amoled-164

[env:waveshare-esp32s3-touch-amoled-164]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv

build_flags =
    -Iinclude
    -Isrc
    -Ofast
    -Wall
    '-D LV_CONF_PATH="${platformio.include_dir}/lv_conf.h"'
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DLV_LVGL_H_INCLUDE_SIMPLE

lib_deps =
    lvgl/lvgl@9.3.0
    moononournation/GFX Library for Arduino@1.6.1
    bogde/HX711@^0.7.5

upload_speed = 921600
monitor_speed = 115200
